Repository essentialkaos/kaos-repo, pull requests merged in 2018-11, with the labels that each got.

#199 Update Consul to 1.3.0
  specs/consul.spec
  specs/consul/SOURCES/consul-client.conf
  specs/consul/SOURCES/consul-client.init
  specs/consul/SOURCES/consul-client.service
  specs/consul/SOURCES/consul-client.sysconfig
  specs/consul/SOURCES/consul-server.conf
  specs/consul/SOURCES/consul-server.init
  specs/consul/SOURCES/consul-server.service
  specs/consul/SOURCES/consul-server.sysconfig
  specs/consul/consul.spec
Labels: PR • IMPROVEMENT

#201 Added python-yaml to Provides for PyYAML and PyYAML34 specs
  specs/PyYAML/PyYAML.spec
  specs/PyYAML/PyYAML34.spec
Labels: PR • FIX

#202 New major zabbix release
  specs/zabbix/SOURCES/config.patch
  specs/zabbix/SOURCES/fonts-config.patch
  specs/zabbix/SOURCES/fping3-sourceip-option.patch
  specs/zabbix/SOURCES/zabbix-agent.init
  specs/zabbix/SOURCES/zabbix-proxy.init
  specs/zabbix/SOURCES/zabbix-proxy.service
  specs/zabbix/SOURCES/zabbix-server.init
  specs/zabbix/SOURCES/zabbix-server.service
  specs/zabbix/SOURCES/zabbix-web22.conf
  specs/zabbix/SOURCES/zabbix-web24.conf
  specs/zabbix/zabbix.spec
Labels: PR • UPDATE
