Repository essentialkaos/kaos-repo, pull requests merged in 2018-07, with the labels that each got.

#189 Fixed python34-tornado version dependency for salt package
  specs/salt/salt.spec
Labels: PR • FIX

#190 Using official perfecto docker image for checking specs on TravisCI
  .linter/rpmlint.conf
  .linter/specs-linter.sh
  .travis.yml
Labels: PR • IMPROVEMENT

#192 Please add Burrow
  specs/Burrow.spec
Labels: PR • NEW

#193 Update Erlang 20 and 21 with patch version
  specs/erlangR20.spec
  specs/erlangR21.spec
Labels: PR • UPDATE
