Repository essentialkaos/kaos-repo, pull requests merged in 2020-02, with the labels that each got.

#230 Add SonarQube 7.9.1 RPM spec
  specs/sonarqube/SOURCES/sonarqube.properties
  specs/sonarqube/SOURCES/sonarqube.service
  specs/sonarqube/SOURCES/sonarqube.sysctl
  specs/sonarqube/sonarqube.spec
  tests/sonarqube/sonarqube-c7.recipe
Labels: PR • NEW

#229 Update Grafana ClickHouse alerting
  specs/grafana/SOURCES/001-grafana-clickhouse-alerting.patch
  specs/grafana/SOURCES/grafana-server.service
  specs/grafana/grafana.spec
Labels: PR • IMPROVEMENT

#232 Release (2020/02/13)
  specs/netatalk/netatalk.spec
  specs/nfs-utils/nfs-utils.spec
  specs/pgbouncer/SOURCES/pgbouncer-ini.patch
  specs/pgbouncer/pgbouncer.spec
  specs/sonarqube/sonarqube.spec
  tests/git.recipe
  tests/libmicrohttpd.recipe
  tests/libverto.recipe
  tests/netatalk/netatalk-c6.recipe
  tests/netatalk/netatalk-c7.recipe
  tests/nfs-utils/nfs-utils-c7.recipe
  tests/prometheus-nodeexporter/prometheus-nodeexporter-c6.recipe
  tests/prometheus-nodeexporter/prometheus-nodeexporter-c7.recipe
  tests/prometheus-pushgateway/prometheus-pushgateway-c6.recipe
  tests/prometheus-pushgateway/prometheus-pushgateway-c7.recipe
  tests/prometheus/prometheus-c6.recipe
  tests/prometheus/prometheus-c7.recipe
Labels: PR • RELEASE
